### ISSUE TITLE
Blank Page on Kirby

### ISSUE THREAD

**Issue by Robertsdesign** [floriankarsten/kirby-plausible#4]
I just get a blank page on my analytics page on Kirby. Is this an issue? Running Kirby 3.8.2. PHP 8.1.12

**Comment by iskrisis** [comment]
Are you sure you set up plausible correctly? I don't think there is any issue with 3.8. i think i run it on multiple sites like this.

**Comment by Robertsdesign** [comment]
this is what I have

`"floriankarsten.plausible" =>  [
    "domain" => "robertsdesign.biz", // used in snippet
    "theme" => "light", // light or dark; used in panel
    "sharedLink" =>
    "https://plausible.io/share/robertsdesign.biz?auth=xxxxxxxxxxxxxxxxx", // used in panel
  ],`

**Comment by iskrisis** [comment]
This look s correct. I don't even think you need to set domain. It seems that on your site (robertsdesign.biz) it is working. I assume when you visit the shared link it works and you are getting trafic on it?

I currently have no 3.8. website with plausible. I will look into updating some and checking if there is problem some day this week (putting this into todo). If it's issue on my side it will be probably some small easy fix.

**Comment by Robertsdesign** [comment]
I fixed the issue! It was a plugin in the browser blocking the page.

**Comment by iskrisis** [comment]
:tada:
