### ISSUE TITLE
Plugin should load when option('debug') !== true instead of option('debug') === false

### ISSUE THREAD

**Issue by ckamper** [floriankarsten/kirby-plausible#5]
Dear Florian, thank you very much for writing this excellent and most useful plugin and providing the Kirby community with it :-)

Just one little thing that tripped me up:

In the snippet it says
`<?php if(option('debug') === false && !kirby()->user()): ?>`

In my config.php, the debug mode is rarely explicitly set to false, but rather commented out like so

`// 'debug' => true,   `

... and I think this is probably true for many Kirby developers, which results in the Plausible script never loading.

So I would suggest changing that line to

`<?php if(option('debug') !== true && !kirby()->user()): ?>`

Thank you

**Comment by iskrisis** [comment]
Makes sense. You probably want to be explicit because of Kirby multi-environment config setup but thats matter of opinion.

**Comment by ckamper** [comment]
Thank you :-)
