### ISSUE TITLE
X-Frame-Options

### ISSUE THREAD

**Issue by KPLehmann** [floriankarsten/kirby-plausible#7]
Hey Florian

The panel doesn't show up in my case, and I get the following console-message:
"refused to display 'https://plausible.io/' in a frame because it set 'X-Frame-Options' to 'sameorigin'." 

Did I maybe not set it up correctly?
Help is much appreciated!
![screenshot](https://user-images.githubusercontent.com/7238594/236442829-8cd52e5f-3a24-4301-9ccc-6982940597c2.png)

**Comment by iskrisis** [comment]
Sorry i am not sure how to help without more context. The plugin should work. What did you put in to the config?

**Comment by KPLehmann** [comment]
Thank you very much for the response! The error was completely on my side. When creating a shared link I didn't know that the password is optional. Without the password protection it works perfectly. Thank you for this great plugin!
